### PR TITLE
Fix the header spacing and lack of spacing on the ratings page

### PR DESCRIPTION
**Pull request by donnchawp**
The Feedback->Crowdsignal page was missing space above the Crowdsignal name in the last release. This patch fixes that.

This patch also fixes the left spacing on Feedback->Ratings page. There wasn't any.

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Sorry... there are bunch of other issues popping up... 

image

... changing the main white background seems to be a dead end ... 😞

**Comment by CGastrell** [comment]
Issue seems to come from a simple CSS priority:
image

This issue has been crawling around since we started sharing styles with CS Forms plugin.

We wrap (as we should) our outer container in a `div.wrap`, this makes things easier for wp-admin as that class comes from the common stylesheet for the admin section. But that class has one specific rule to make the left margin of 20px.

Whenever we override that `.wrap` class, things start to go south. Solution-ish to the issue would be to either append `!important` on `.polls-wrap` declaration or make `.polls-wrap` more specific (`.wrap.polls-wrap`). But that wouldn't fix the same issue seen on Settings -> Crowdsignal (coming from CS Forms) as the wrapper doesn't hold the `.polls-wrap` class. 

Another option would be to apply any *wrapper* style to `#manage-polls` which, albeit it's name, is used to wrap everything on both our plugins. Then again, we need an exception to the Ratings settings/list views, as those are still on the old/legacy style (yes, there is a `.ratings-wrap` to reset the left-margin, but it doesn't get applied to the settings, only the list view).

So, step 1, re-define the `#manage-polls` style:
```
#manage-polls {
	margin-right: 0;
	margin-top: 0;
}
#manage-polls:not(.ratings-wrap) {
	margin-left: -20px;
}
```

Step 2, add that `.ratings-wrap` to the ratings settings page the same way `$wrap_style` was added on management page, line 1686 would read:
```
		$wrap_style = $page === 'crowdsignal-settings' ? 'polls' : 'ratings';
		?>
		<div class="wrap <?php echo $wrap_style . '-wrap'; ?>" id="manage-polls">
```

**Comment by digitalwaveride** [comment]
Side spacing is gone for me! 🥳 

image

**Review by digitalwaveride — APPROVED** [review]
🚀 Left-side padding issue is gone!

**Pull request merged**
