### PR TITLE
The menu showed still a Polldaddy Icon. Exchanged it with Crowdsignal…

### PR DESCRIPTION
**Pull request by digitalwaveride**
Changed the Polldaddy icon font, for a Crowdsignal icon font.

Before:

before

After:

before

### CODE REVIEW

**Comment by CGastrell** [comment]
Nice! Should we remove the meta tags from the svg file?
```
<metadata>Generated by IcoMoon</metadata>
```

**Comment by donnchawp** [comment]
It's almost there. You need to make the filenames in polldaddy-icons.css start with an uppercase C or rename the font files so they're all lowercase.
The #crowdsignal on the svg line is fine as lowercase.

**Comment by digitalwaveride** [comment]
@CGastrell also removed the meta tags line. Thanks!

**Comment by donnchawp** [comment]
Merged, thanks @digitalwaveride !

**Pull request merged**
