### PR TITLE
Remove Jetpack CSS and fix disconnect script. Update version

### PR DESCRIPTION
**Pull request by donnchawp**
This patch removes our dependency on the Jetpack CSS and renames all elements so there shouldn't be any conflict.

It also adds code to disconnect the blog from Crowdsignal.

Bumped the version to 3.0.5

### CODE REVIEW

**Review by CGastrell — CHANGES_REQUESTED** [review]
The main scope of the changeset looks fine to me.

Just a couple of notes/observations so I get this right

- we got rid of the legacy PD settings and its options
- we get same setup UI for both PD and CS Forms

Maybe unrelated, but I disconnected, then visited the Ratings settings and it just shows the title "Rating settings", rest of the page is blank.

We fixed this typo on CS Forms, it would be good have it here as well: The setup process start reads "respones" instead of "responses":
image

So, let me know if you prefer to address these 2 on another PR and we'll give this one green light

**Comment by digitalwaveride** [comment]
Ratings page worked for me (even though with the slightly broken CSS, but that is an existing issue, seeing it on Atomic sites right now) + the ratings page has also a weird scrolling state ... I have to scroll upwards to see the top content of the rating settings. We should address these in a separate PR.

image

**Comment by digitalwaveride** [comment]
Overall things worked for me.
Just the "Advanced Settings" link had no chevron or arrow ... 
image

But should be not a blocker at that point.

**Comment by CGastrell** [comment]
> Ratings page worked for me (even though with the slightly broken CSS, but that is an existing issue, seeing it on Atomic sites right now) + the ratings page has also a weird scrolling state

Yeah, noticed that as well. I didn't have to scroll to see the content, but I see the scrollbar present as if the content was higher than the container (which clearly shouldn't be the case)

I think the `#manage-polls { height: 100%; }` doesn't make sense anymore

**Pull request merged**
